<script setup lang="ts">
import ModeIcon from "@/components/icons/Mode.vue";
import ModeButton from "./ModeButton.vue";
</script>

<template>
  <nav
    bg-white
    px-2
    sm:px-4
    py-2.5
    dark:bg-gray-900
    fixed
    w-full
    z-20
    top-0
    left-0
    border-b
    border-gray-200
    dark:border-gray-600
  >
    <div container flex flex-wrap justify-between items-center mx-auto>
      <a href="javascript:;" flex items-center>
        <span
          self-center
          text-3xl
          font-semibold
          whitespace-nowrap
          text-cyan-500
          dark:text-cyan-100
          >InkFish</span
        >
      </a>
      <div flex md:order-2>
        <ModeButton />
        <button
          data-collapse-toggle="navbar-sticky"
          type="button"
          inline-flex
          items-center
          p-2
          text-sm
          text-gray-500
          rounded-lg
          md:hidden
          hover:bg-gray-100
          focus:outline-none
          focus:ring-2
          focus:ring-gray-200
          dark:text-gray-400
          dark:hover:bg-gray-700
          dark:focus:ring-gray-600
          aria-controls="navbar-sticky"
          aria-expanded="false"
        >
          <span sr-only>Open main menu</span>
          <svg
            w-6
            h-6
            aria-hidden="true"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </button>
      </div>
      <div
        hidden
        justify-between
        items-center
        w-full
        md:flex
        md:w-auto
        md:order-1
        id="navbar-sticky"
      >
        <ul
          flex
          flex-col
          p-4
          mt-4
          bg-gray-50
          rounded-lg
          border
          border-gray-100
          md:flex-row
          md:space-x-8
          md:mt-0
          md:text-sm
          md:font-medium
          md:border-0
          md:bg-white
          dark:bg-gray-800
          md:dark:bg-gray-900
          dark:border-gray-700
        >
          <li>
            <a
              block
              py-2
              pr-4
              pl-3
              text-white
              bg-blue-700
              rounded
              md:bg-transparent
              md:text-blue-700
              md:p-0
              dark:text-white
              href="#"
              aria-current="page"
              >Home</a
            >
          </li>
          <li>
            <a
              block
              py-2
              pr-4
              pl-3
              text-gray-700
              rounded
              hover:bg-gray-100
              md:hover:bg-transparent
              md:hover:text-blue-700
              md:p-0
              md:dark:hover:text-white
              dark:text-gray-400
              dark:hover:bg-gray-700
              dark:hover:text-white
              md:dark:hover:bg-transparent
              dark:border-gray-700
              href="#"
              >About</a
            >
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>
